/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c9667a20-c92d-4702-8806-5a64b8919b07",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_wrGgO8XUQ",
    "aws_user_pools_web_client_id": "bjp3lkmi6ulkpdgjpb5l9dpbl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://isqorycnxjbhpo2k6orjloplt4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "gsstorelogo115246-devgs",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
